<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="POGONOPHILE" failures="0" tests="3" name="tests.TC01_LoginTestCase" time="2.337" errors="1" timestamp="2023-06-09T18:12:50 IST" skipped="0">
  <testcase classname="tests.TC01_LoginTestCase" name="validateAllTheElements" time="0.148"/>
  <system-out/>
  <testcase classname="tests.TC01_LoginTestCase" name="loginWithValidCredentials" time="0.923">
    <error message="
[public void tests.TC01_LoginTestCase.loginWithValidCredentials(java.lang.String,java.lang.String)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: loginWithValidCredentials([java.lang.String arg0, java.lang.String arg1])
Arguments: [(java.lang.String) Ram,(java.lang.String) Mr,(java.lang.String) Kumar,(java.lang.String) R,(java.lang.String) Male,(java.lang.String) Full-time,(java.lang.Integer) 10,(java.lang.Integer) 29,(java.lang.Integer) 1998,(java.lang.String) Single,(java.lang.Integer) 1,(java.lang.String) ram,(java.lang.String) ram,(java.lang.String) Praviram2910]" type="org.testng.internal.reflect.MethodMatcherException">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void tests.TC01_LoginTestCase.loginWithValidCredentials(java.lang.String,java.lang.String)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: loginWithValidCredentials([java.lang.String arg0, java.lang.String arg1])
Arguments: [(java.lang.String) Ram,(java.lang.String) Mr,(java.lang.String) Kumar,(java.lang.String) R,(java.lang.String) Male,(java.lang.String) Full-time,(java.lang.Integer) 10,(java.lang.Integer) 29,(java.lang.Integer) 1998,(java.lang.String) Single,(java.lang.Integer) 1,(java.lang.String) ram,(java.lang.String) ram,(java.lang.String) Praviram2910]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:46)
at org.testng.internal.Parameters.injectParameters(Parameters.java:909)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:37)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- loginWithValidCredentials -->
  <system-out/>
  <testcase classname="tests.TC01_LoginTestCase" name="loginWithInvalidCredentials" time="1.266"/>
  <system-out/>
</testsuite> <!-- tests.TC01_LoginTestCase -->
